package com.example.lab5_starter;

import android.os.Bundle;
import android.util.Log;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ListView;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity implements CityDialogFragment.CityDialogListener {

    private Button addCityButton;
    private ListView cityListView;

    private ArrayList<City> cityArrayList;
    private ArrayAdapter<City> cityArrayAdapter;

    private FirebaseFirestore db;
    private CollectionReference citiesRef;

    // Variable to track which city has been clicked
    // Initialize to -1 for none selected
    int selectedIdx = -1;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main);
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);

            return insets;
        });

        // Set views
        addCityButton = findViewById(R.id.buttonAddCity);
        cityListView = findViewById(R.id.listviewCities);

        // create city array
        cityArrayList = new ArrayList<>();
        cityArrayAdapter = new CityArrayAdapter(this, cityArrayList);
        cityListView.setAdapter(cityArrayAdapter);

        // addDummyData();

        // set listeners
        addCityButton.setOnClickListener(view -> {
            CityDialogFragment cityDialogFragment = new CityDialogFragment();
            cityDialogFragment.show(getSupportFragmentManager(), "Add City");
        });

        cityListView.setOnItemClickListener((adapterView, view, i, l) -> {
            City city = cityArrayAdapter.getItem(i);
            selectedIdx = i;
            CityDialogFragment cityDialogFragment = CityDialogFragment.newInstance(city);
            cityDialogFragment.show(getSupportFragmentManager(), "City Details");
        });

        db = FirebaseFirestore.getInstance();
        citiesRef = db.collection("cities");

        citiesRef.addSnapshotListener((value, error) -> {
            if (error != null) {
                Log.e("Firestore", error.toString());
            }
            if (value != null && !value.isEmpty()) {
                cityArrayList.clear();
                for (QueryDocumentSnapshot snapshot : value) {
                    String name = snapshot.getString("name");
                    String province = snapshot.getString("province");

                    cityArrayList.add(new City(name, province));
                }
                // This line was generated to be here by Gemini 3, Google DeepMind
                // I fed it this file along with "this is my code for the mainactivity file.
                // I tried adding the loop section from addSnapshotListener to onCreate but it didn't work"
                // 26/02/05 3:44 PM
                cityArrayAdapter.notifyDataSetChanged();  // Added as data was not being pulled from Firebase upon initialization
            }
        });
    }

    // The following function was generated by Gemini 3, Google DeepMind
    // "im thinknig of using the methods we already have
    //public void updateCity(City city, String title, String year) {
    //    removeCity(city);
    //
    //    addCity(new City city(title, year));
    //    city.setName(title);
    //    city.setProvince(year);
    //    cityArrayAdapter.notifyDataSetChanged();
    //
    //    // Updating the database using delete + addition
    //    DocumentReference docRef = citiesRef.document(city.getName());
    //    docRef.set(city);
    //}"
    // 26/02/05, 4:04 PM
    @Override
    public void updateCity(City city, String title, String year) {
        /** Note: I updated this function to ensure updating the city info would also have firebase
            persistence as it didn't before. (i think)
         */
        // Remove old city from local and cloud
        removeCity(city);

        // Create new city with new name and province
        City updatedCity = new City(title, year);

        // Update Firebase DB with new city
        addCity(updatedCity);
    }
    @Override
    public void addCity(City city) {
        cityArrayList.add(city);
        // Note: I removed cityArrayAdapter.notifyDataSetChanged(); as I added it to snapshot listener

        DocumentReference docRef = citiesRef.document(city.getName());
        docRef.set(city);
    }

    @Override
    public void removeCity(City city) {
        // Remove city from local data
        cityArrayList.remove(selectedIdx);
        selectedIdx = -1;

        // Update firebase DB
        DocumentReference docRef = citiesRef.document(city.getName());
        docRef.delete();
    }

    public void addDummyData() {
        City m1 = new City("Edmonton", "AB");
        City m2 = new City("Vancouver", "BC");
        cityArrayList.add(m1);
        cityArrayList.add(m2);
        cityArrayAdapter.notifyDataSetChanged();
    }
}